pip install requests
pip install pandas
pip install openpyxl
pip install lxml
pip install pyarrow
pip install selenium
pip install bs4
pip install eventregistry
pip install fuzzywuzzy
pip install python-Levenshtein